### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by azazellochg** [MPI-Dortmund/tomotwin-cryoet#1]
Hi @thorstenwagner ! I'm looking at https://tomotwin-cryoet.readthedocs.io/en/latest/tutorials/tutorials_overview.html#tutorial-1-reference-based-particle-picking. I understand this repo is still work in progress, but I got a few questions:

- is it normal for tomo embedding to take hours? I'm embedding model8 tomo (512x512x512) and it takes 1.5h on 1 gpu with 256 batch size and Z range 200-250px. Full tomo takes over 8 hours to embed on 4 gpus.
- is napari-boxmanager released? I couldn't find it anywhere..
- map, locate and pick commands run only on CPU? I see tomotwin_locate has 4 CPUs hardcoded.

**Comment by thorstenwagner** [comment]
Hi Grigory,

> is it normal for tomo embedding to take hours? I'm embedding model8 tomo (512x512x512) and it takes 1.5h on 1 gpu with 256 batch size and Z range 200-250px. Full tomo takes over 8 hours to embed on 4 gpus.

Calculating the embeddings is definitely computational expensive, but your timings appear far to high for me.

Here some timings from me (2x TitanV) for the 512x512x512 tomogram:
 - One GPU, Full 512x512x512, batchsize 200, no ssd: 4h
 - Two GPUs, Full 512x512x512, batchsize 400, no ssd: : 2.5h
 
Now with Z range 200-250px:
 - One GPU, Full 512x512x512, batchsize 200, no ssd: 26 min
 - Two GPUs, Full 512x512x512, batchsize 400, no ssd: : 15 min

With a parallel file system and A100 GPUs its about 2x-3x as fast (fore each scenario).

However, the way we parallelized the calculations of the embedding is not optimal yet, as it can be limited due to the global interpreter lock of python. Its already on my list of necessary changes, but it does have the highest priority for me. Anyway, I don't think that this is the reason for your bad timings.

What GPUs do you use? Do they support half precision? Because that is automatically used if available and could have a huge impact.

> is napari-boxmanager released? I couldn't find it anywhere..

We are finalizing it right now. It will not only be the central GUI for TomoTwin but will also replace the nasty cryolo boxmanager ( PSSST ;-) - thats not yet announced ). It will be open source as TomoTwin. @mstabrin is the main developer of that tool. Maybe we can put it already on GitHub - however, we have not yet written all the documentation and not all export formats are implemented yet.

> map, locate and pick commands run only on CPU? I see tomotwin_locate has 4 CPUs hardcoded.

Yes, CPU. Thanks for reminding me for the hard coded 4. I used 4 because otherwise I run into memory issues for some datasets. I will make it an argument but with default set to 4.

**Comment by azazellochg** [comment]
Hi,

I'm running full range
```
source /public/EM/Scipion/conda.rc&& conda activate tomotwin-0.1.0 && CUDA_VISIBLE_DEVICES=0,1 tomotwin_embed.py tomogram -m /public/EM/Scipion/scipion-dev/software/em/tomotwin_model-052022/tomotwin_model_p120_052022.pth -v reconstruction.mrc -b 256 -o embed/tomos -w 37 -s 2
```

on a 512 size tomo. On 2x Tesla T4 is takes 7h. This is no SSD, but the data is on parallel ceph file system. Once I sort out my queue problems I can check on 4x RTX2080ti +/- SSD. I also have A100-40 and A100-80. I dont know about half-precision thing..

**Comment by thorstenwagner** [comment]
I checked, T4 is supporting FP16 (half precision).

**Comment by thorstenwagner** [comment]
Hm, for me its even faster with one GPU and no SSD?

**Comment by azazellochg** [comment]
Could this be related to the fact that I installed cudatoolkit 11.6.0 but run with the 11.4 drivers?

**Comment by thorstenwagner** [comment]
I'm also using CUDA Drivers 11.4 locally, so I don't think that this is the problem.

Did you got the same results with the A100?

**Comment by azazellochg** [comment]
My queue submission is broken. Besides 2080Ti I could only test on 2x3090 and it takes 40min to embed Z 200-240px of 512px volume

**Comment by azazellochg** [comment]
Hi @thorstenwagner , I got a few more questions:
1) embedding is not using the correct GPU: 
```
source /public/EM/Scipion/conda.rc&& conda activate tomotwin-0.1.0 && CUDA_VISIBLE_DEVICES=1 tomotwin_embed.py tomogram -m /public/EM/Scipion/scipion-dev/software/em/tomotwin_model-052022/tomotwin_model_p120_052022.pth -v emd_10439.mrc -b 256 -o embed/tomos -w 44 -s 2 -z 200 240
00027:   reading /public/EM/Scipion/scipion-dev/software/em/tomotwin_model-052022/tomotwin_model_p120_052022.pth
00028:   Model config:
00029:   {'identifier': 'SiameseNet', 'network_config': {'output_channels': 32, 'dropout': 0.2, 'repeat_layers': 0, 'norm_name': 'GroupNorm', 'norm_kwargs': {'num_groups': 64, 'num_channels': 1024}, 'gem_pooling_p': 0}, 'train_config': {'loss': 'TripletLoss', 'tl_margin': 0.539, 'miner': True, 'miner_margin': 0.734, 'learning_rate': 5.945e-05, 'optimizer': 'Adam', 'weight_decay': 0, 'batchsize': 35, 'patience': 50, 'aug_train_shift_distance': 2}, 'distance': 'COSINE'}
``` 

fails with 
```
RuntimeError: CUDA out of memory. Tried to allocate 5.56 GiB (GPU 0; 14.76 GiB total capacity; 8.81 GiB already allocated; 4.94 GiB free; 8.88 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
2. Are the window size for embedding and box size for locate should be the same? Should the match input references size?

**Comment by thorstenwagner** [comment]
Hi @azazellochg 

sorry that it took me so long.

As for 1:

Did you checked that with nvidia-smi?  Because on my side it is using the correct gpu (with `CUDA_VISIBLE_DEVICES=1`). However, If I use a super large batch size to produce an out of memory error I also get reported that GPU 0 is crashing. I think internally it is GPU 0, because it has only 1 GPU visible. But nvidia-smi clearly shows that is is using the correct GPU.

As for 2:

The windows size should match the one used during training (37, whyOwhy a prime number ^^). I will simply remove this parameter and save the used window size in metadata of the model. Thanks for making me aware of this. The box size for locate only influences the non maximum suppression. The ideal box size is a tight box size around the protein.

As for speed: 

I think we have 3080s around. I can measure timings for them as well. Would that be helpful?

**Comment by azazellochg** [comment]
1) you are right! I should have checked that, apologies. It does run on the specified gpu.
2) got it, thanks! I'll remove window size as well from scipion protocol
3) Running a test now on 1xTesla T4 15Gb memory: embedding of 928x928x500 13.7A/px tomo Z range 200-240
```00053:   Calculate embeddings:   0%|          | 46/15541 [00:44<3:50:30,  1.12it/s]```

**Comment by thorstenwagner** [comment]
What is the GPU utilization during the test?

**Comment by azazellochg** [comment]
|   1  Tesla T4            On   | 00000000:ED:00.0 Off |                    0 |
| N/A   75C    P0    64W /  70W |  12714MiB / 15109MiB |    100%      Default

**Comment by thorstenwagner** [comment]
@GavinR1 also run a test on model 8 with RTX 2080 Ti, SSD,  z range 200-250:

1xGPU, batch size 128: 36 min
2xGPU, batch size 256: 26 min

**Comment by thorstenwagner** [comment]
```
4x 2080Ti no SSD, range 200-250 - 30min. I'll try with SSD, maybe that's the bottleneck.
```
What was the batch size here? I assume that 256 is not enough and use 512.

**Comment by azazellochg** [comment]
It was 256. Could you show your packages versions (conda list)?

**Comment by thorstenwagner** [comment]
[tt_env.txt](https://github.com/MPI-Dortmund/tomotwin-cryoet/files/9478446/tt_env.txt)

**Comment by azazellochg** [comment]
Hm, I'm missing all of these:
```
nvidia-cublas-cu11        2022.4.8                 pypi_0    pypi
nvidia-cublas-cu117       11.10.1.25               pypi_0    pypi
nvidia-cuda-runtime-cu11  2022.4.25                pypi_0    pypi
nvidia-cuda-runtime-cu117 11.7.60                  pypi_0    pypi
nvidia-cudnn-cu11         2022.5.19                pypi_0    pypi
nvidia-cudnn-cu116        8.4.0.27                 pypi_0    pypi
nvidia-tensorrt           8.4.3.1                  pypi_0    pypi
```

I used the following to install things:
```
conda create -y -n {ENV_NAME} -c pytorch -c rapidsai -c nvidia -c conda-forge python=3.9 pytorch==1.12 torchvision pandas scipy numpy matplotlib pytables cuML=22.06 cudatoolkit=11.6 'protobuf>3.20' tensorboard && conda activate tomotwin-{version} && pip install -e . && conda remove -y --force cupy
```

**Comment by thorstenwagner** [comment]
I made a fresh install and those packages disappeared. But the timings are still the same on my machine. 

Here is the environment fresh after installation:
[env.txt](https://github.com/MPI-Dortmund/tomotwin-cryoet/files/9478708/env.txt)

**Comment by azazellochg** [comment]
Here is mine [tt.txt](https://github.com/MPI-Dortmund/tomotwin-cryoet/files/9478756/tt.txt) Cant see anything different..

**Comment by thorstenwagner** [comment]
Just to have a comparison with the same parameters:

Could you run it on a single 2080 with a batch size of 128 like I did?

02.09.2022 16:37:04 Grigory Sharov ***@***.***>:

**Comment by azazellochg** [comment]
I had two problems: 1) I had 4 gpus used by tomotwin instead of 1 (slurm is overwriting CUDA_VISIBLE_DEVICES) 2) i was submitting to either 1080ti or 2080ti nodes. So I think double time comes from 1080ti runs. Sorry for all the mess!
